---

- name: Delete application resources folder
  file: "state=absent path={{ app_resources_folder }}"
  run_once: true

- name: Create application resources folder
  file: "state=directory path={{ app_resources_folder }}"

- name: Copy application resources
  copy: src="{{ app_resources_src }}"
       dest="{{ app_resources_folder }}"
  run_once: true
