apiVersion: v1
data:
  JOB_UTKASTLOCK_CRON: "10 3 * * * ?"
  JOB_UTKASTLOCK_LOCKED_AFTER_DAY: "14"
  CONFIG_DIR: "${config.folder}"
  LOGBACK_FILE: "/opt/$APP_NAME/config/logback-ocp.xml"
  REDIS_HOST: "ind-sint-redis1.ind1.sth.basefarm.net;ind-sint-redis2.ind1.sth.basefarm.net;ind-sint-redis3.ind1.sth.basefarm.net"
  REDIS_PORT: "26379;26379;26379"
  REDIS_SENTINEL_MASTER_NAME: "ind-sint-redis"
  MAIL_FROM: "no-reply@verifiering.webcert.intygstjanster.se"
  MAIL_PROTOCOL: "smtp"
  MAIL_USERNAME: ""
  SPRING_PROFILES_ACTIVE: "qa,wc-security-test,wc-all-stubs,testability-api,webcertMainNode,caching-enabled,redis-sentinel"
  SAKERHETSTJANST_SAML_KEYSTORE_ALIAS: "verifiering.intygstjanster.sjunet.org"
  DATABASE_PORT: "3306"
  DATABASE_SERVER: "ind-sint-mysqlvip.ind1.sth.basefarm.net"
  ACTIVEMQ_BROKER_URL: "failover:(tcp://ind-sint-activemq1.ind1.sth.basefarm.net:61616,tcp://ind-sint-activemq2.ind1.sth.basefarm.net:61616)?jms.nonBlockingRedelivery=true&jms.redeliveryPolicy.useExponentialBackOff=true&jms.redeliveryPolicy.backOffMultiplier=2&jms.redeliveryPolicy.maximumRedeliveries=30&jms.redeliveryPolicy.maximumRedeliveryDelay=3600000&jms.redeliveryPolicy.initialRedeliveryDelay=60000"
  NOTIFICATION_QUEUENAME: "webcert.notification.queue"
  NOTIFICATION_WS_QUEUENAME: "webcert.notification.ws.queue"
  NOTIFICATION_AGGREGATION_QUEUENAME: "webcert.aggregated.notification.queue"
  LOG_QUEUENAME: "webcert.log.queue"
  CERTIFICATE_SENDER_QUEUENAME: "webcert.certificate.queue"
  CERTIFICATE_SENDER_QUEUEMAME: "webcert.certificate.queue"
  NTJP_WS_CERTIFICATE_FILE: "${certificate.folder}/verifiering.webcert.intygstjanster.sjunet.org_autentisering.p12"
  NTJP_WS_TRUSTSTORE_FILE: "${certificate.folder}/truststore.jks"
  NTJP_WS_CERTIFICATE_TYPE: "PKCS12"
  NTJP_WS_TRUSTSTORE_TYPE: "JKS"
  CGI_GRP_WS_CERTIFICATE_FILE: "${certificate.folder}/verifiering.webcert.intygstjanster.sjunet.org_autentisering.p12"
  CGI_GRP_WS_CERTIFICATE_TYPE: "PKCS12"
  CGI_GRP_WS_TRUSTSTORE_FILE: "${certificate.folder}/cgi-truststore.jks"
  CGI_GRP_WS_TRUSTSTORE_TYPE: "JKS"
  SAKERHETSTJANST_SAML_IDP_METADATA_URL: "https://idp2.acctest.sakerhetstjanst.inera.se:443/idp/saml"
  SAKERHETSTJANST_SAML_KEYSTORE_FILE: "file://${certificate.folder}/saml-keystore.jks"
  WEBCERT_HOST_URL: "https://verifiering.webcert.intygstjanster.se"
  INTYGSTJANST_BASE_URL: "http://intygstjanst:8080/inera-certificate"
  FMB_ENDPOINT_URL: "https://api.socialstyrelsen.se/fmb"
  NETID_ACCESS_SERVER_URL: "https://showroom.lab.secmaker.com/nias/ServiceServer.asmx"
  NTJP_BASE_URL: "https://qa.esb.ntjp.se/vp"
  SRS_BASE_URL: "${webcert.host.url}/services/stubs"
  PRIVATEPRACTITIONER_BASE_URL: "http://privatlakarportal:8080/services"
  PRIVATEPRACTITIONER_PORTAL_REGISTRATION_URL: "https://verifiering.registrering.intygstjanster.se"
  CGI_FUNKTIONSTJANSTER_SAML_IDP_METADATA_URL: "https://m00-mg-local.testidp.funktionstjanster.se/samlv2/idp/metadata/0/10"
  CGI_FUNKTIONSTJANSTER_GRP_URL: "https://grpt.funktionstjanster.se:18898/grp/v1"
  CGI_GRP_SERVICEID: "logtest007"
  CGI_GRP_DISPLAYNAME: "Funktionstj\u00E4nster Test"
  TAK_BASE_URL: "http://api.ntjp.se/coop/api/v1"
  TAK_ENVIRONMENT: "QA"
  INFRASTRUCTURE_DIRECTORY_LOGICALADDRESS: "SE165565594230-1000"
  INTYGSTJANST_LOGICALADDRESS: "5565594230"
  PRIVATEPRACTITIONER_LOGICALADDRESS: ""
  PUTJANST_LOGICALADDRESS: "SE165565594230-1000"
  SENDANSWERTOFK_LOGICALADDRESS: "Test"
  SENDQUESTIONTOFK_LOGICALADDRESS: "Test"
  SENDMESSAGETOFK_LOGICALADDRESS: "NMTMOCKS"
  MAIL_HOST: "mailout.sth.basefarm.net"
kind: ConfigMap
metadata:
  name: webcert-configmap-envvar
type: Opaque
