apiVersion: v1
stringData:
  ACTIVEMQ_BROKER_USERNAME: "UsrIntyg"
  ACTIVEMQ_BROKER_PASSWORD: xxxxxxx
  MAIL_PASSWORD: xxxxxxx
  DATABASE_USERNAME: "webcert"
  DATABASE_PASSWORD: xxxxxxx
  CGI_GRP_WS_CERTIFICATE_PASSWORD: xxxxxxx
  CGI_GRP_WS_KEY_MANAGER_PASSWORD: xxxxxxx
  CGI_GRP_WS_TRUSTSTORE_PASSWORD: xxxxxxx
  HSA_WS_CERTIFICATE_PASSWORD: xxxxxxx
  HSA_WS_KEY_MANAGER_PASSWORD: xxxxxxx
  HSA_WS_TRUSTSTORE_PASSWORD: xxxxxxx
  IDP_OIDC_CLIENT_ID: xxxxxxx
  IDP_OIDC_CLIENT_SECRET: xxxxxxx
  NTJP_WS_CERTIFICATE_PASSWORD: xxxxxxx
  NTJP_WS_KEY_MANAGER_PASSWORD: xxxxxxx
  NTJP_WS_TRUSTSTORE_PASSWORD: xxxxxxx
  SAKERHETSTJANST_SAML_KEYSTORE_PASSWORD: xxxxxxx
  SAKERHETSTJANST_SAML_TRUSTSTORE_PASSWORD: xxxxxxx
  SAKERHETSTJANST_WS_CERTIFICATE_PASSWORD: xxxxxxx
  SAKERHETSTJANST_WS_KEY_MANAGER_PASSWORD: xxxxxxx
  SAKERHETSTJANST_WS_TRUSTSTORE_PASSWORD: xxxxxxx
kind: Secret
metadata:
  name: webcert-secret-envvar
type: Opaque
