apiVersion: v1
data:
  SPRING_PROFILES_ACTIVE: "test,wc-all-stubs,wc-security-test,testability-api,caching-enabled"
  WEBCERT_HOST_URL: "https://demo.webcert.intygstjanster.se"
  INTYGSTJANST_BASE_URL: "http://intygstjanst:8080/inera-certificate"
  PRIVATEPRACTITIONER_PORTAL_REGISTRATION_URL: "https://demo.registrering.intygstjanster.se/#/"
  NTJP_BASE_URL: "http://127.0.0.1:8080/services/stubs"
  TAK_BASE_URL: "${ntjp.base.url}/takstub"
  SRS_BASE_URL: "${ntjp.base.url}"
  PRIVATEPRACTITIONER_BASE_URL: "${ntjp.base.url}"
  FMB_ENDPOINT_URL: "https://api.socialstyrelsen.se/fmb"
  NETID_ACCESS_SERVER_URL: "https://showroom.lab.secmaker.com/nias/ServiceServer.asmx?WSDL"
  SAKERHETSTJANST_SAML_IDP_METADATA_URL: "https://idp2.acctest.sakerhetstjanst.inera.se/idp/saml"
  TAK_ENVIRONMENT: "DEV"
  SENDQUESTIONTOFK_LOGICALADDRESS: "SendQuestionStub"
  SENDMESSAGETOFK_LOGICALADDRESS: "SendMessageStub"
  SENDANSWERTOFK_LOGICALADDRESS: "SendAnswerStub"
  PUTJANST_LOGICALADDRESS: "SE165565594230-1000"
  INTYGSTJANST_LOGICALADDRESS: "TEST0001"
  PRIVATEPRACTITIONER_LOGICALADDRESS: ""
  INFRASTRUCTURE_DIRECTORY_LOGICALADDRESS: "SE165565594230-1000"
  NTJP_WS_CERTIFICATE_FILE: "${certificate.folder}/verifiering.webcert.intygstjanster.sjunet.org_autentisering.p12"
  NTJP_WS_CERTIFICATE_TYPE: "PKCS12"
  NTJP_WS_TRUSTSTORE_FILE: "${certificate.folder}/truststore.jks"
  NTJP_WS_TRUSTSTORE_TYPE: "JKS"
  CGI_GRP_WS_CERTIFICATE_FILE: "${certificate.folder}/test.intygstjanster.sjunet.org.jks"
  CGI_GRP_WS_CERTIFICATE_TYPE: "JKS"
  CGI_GRP_WS_TRUSTSTORE_FILE: "${certificate.folder}/grp.test.truststore.jks"
  CGI_GRP_WS_TRUSTSTORE_TYPE: "JKS"
  SAKERHETSTJANST_SAML_KEYSTORE_FILE: "file://${certificate.folder}/verifiering.webcert.intygstjanster.sjunet.org_autentisering.p12"
  SAKERHETSTJANST_SAML_KEYSTORE_ALIAS: "test.intygstjanster.sjunet.org"
  SAKERHETSTJANST_SAML_TRUSTSTORE_FILE: "file://${certificate.folder}/truststore.jks"
  CGI_FUNKTIONSTJANSTER_SAML_IDP_METADATA_URL: "https://m00-mg-local.testidp.funktionstjanster.se/samlv2/idp/metadata/0/10"
  CGI_FUNKTIONSTJANSTER_GRP_URL: "${webcert.host.url}/services/grp"
  CGI_GRP_SERVICEID: "logtest007"
  CGI_GRP_DISPLAYNAME: "Test"
  ACTIVEMQ_BROKER_URL: "${activemq.amq.tcp.port}?jms.nonBlockingRedelivery=true&jms.redeliveryPolicy.maximumRedeliveries=3&jms.redeliveryPolicy.maximumRedeliveryDelay=6000&jms.redeliveryPolicy.initialRedeliveryDelay=4000&jms.redeliveryPolicy.useExponentialBackOff=true&jms.redeliveryPolicy.backOffMultiplier=2"
  CERTIFICATE_SENDER_QUEUENAME: "demo.webcert.certificate.queue"
  NOTIFICATION_WS_QUEUENAME: "demo.webcert.notification.ws.queue"
  NOTIFICATION_QUEUENAME: "demo.webcert.notification.queue"
  NOTIFICATION_AGGREGATION_QUEUENAME: "demo.webcert.aggregated.notification.queue"
  REDIS_HOST: "${redis.service.host}"
  REDIS_PORT: "${redis.service.port}"
  DATABASE_NAME: "webcert"
  DATABASE_SERVER: "${mysql.service.host}"
  DATABASE_PORT: "${mysql.service.port}"
  LOG_QUEUENAME: "demo.log.queue"
  CONFIG_DIR: "${config.folder}"
  RESOURCES_DIR: "${resources.folder}"
  MAIL_HOST: ""
  REDIS_KEY_TTL: "3600"
kind: ConfigMap
metadata:
  name: webcert-demo-configmap-envvar
type: Opaque
