apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: webcert
  name: webcert
spec:
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: webcert:latest
  resources: {}
  source:
    git:
      ref: feature/openshift
      uri: https://github.com/sklintyg/webcert.git
    contextDir: /
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: "BUILD_LOGLEVEL"
        value: "2"
      - name: commonVersion
        value: 3.6.0.+
      - name: infraVersion
        value: 3.6.0.+
      - name: buildVersion
        value: 6.0.0.0-OPENSHIFT
      from:
        kind: "ImageStreamTag"
        name: "intyg-s2i:latest"
      forcePull: true

