apiVersion: v1
kind: Service
metadata:
  labels:
    app: webcert
  name: webcert
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 5006-tcp
    port: 5006
    protocol: TCP
    targetPort: 5006
  selector:
    deploymentconfig: webcert
  sessionAffinity: None
  type: ClusterIP
